apiVersion: apps/v1
kind: Deployment
metadata:
  name: frank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frank-api
  template:
    metadata:
      labels:
        app: frank-api
    spec:
      containers:
        - name: frank-api
          image: us-central1-docker.pkg.dev/cit262-416322/frank-api/api-test
          ports:
          - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10